//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCreationForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartProperty
    {
        public string CartId { get; set; }
        public string EmployeeId { get; set; }
        public string CartType { get; set; }
        public int GroupNum { get; set; }
        public bool IsComplete { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
