//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCreationForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.CartProperties = new HashSet<CartProperty>();
            this.Requisitions = new HashSet<Requisition>();
            this.RequisitionApprovers = new HashSet<RequisitionApprover>();
        }
    
        public string EmployeeId { get; set; }
        public string EmployeeFname { get; set; }
        public string EmployeeLname { get; set; }
        public int EmployeeStatusId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime EmpDateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartProperty> CartProperties { get; set; }
        public virtual Department Department { get; set; }
        public virtual EmployeeStatusType EmployeeStatusType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionApprover> RequisitionApprovers { get; set; }
    }
}
