//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCreationForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLimitPerDept
    {
        public int DepartmentId { get; set; }
        public string Personnel { get; set; }
        public int TotalFigures { get; set; }
        public int FirstFigure { get; set; }
        public int SecondFigure { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
