//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCreationForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailsNo { get; set; }
        public string CartId { get; set; }
        public decimal GrandTotal { get; set; }
        public int RequisitionNo { get; set; }
        public System.Guid DocGUID { get; set; }
        public byte[] QuotationFile { get; set; }
    }
}
