//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCreationForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public int RecordId { get; set; }
        public int RequsitionNo { get; set; }
        public string EmployeeId { get; set; }
        public string OrderStatus { get; set; }
        public decimal OrderTotal { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ApprovalStatusId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string CheckedBy { get; set; }
        public string AuthorizedBy { get; set; }
        public string InvoiceNo { get; set; }
        public System.Guid FileGUID { get; set; }
        public byte[] InvoiceFile { get; set; }
        public string Comments { get; set; }
        public bool IsComplete { get; set; }
    
        public virtual ApprovalStatusType ApprovalStatusType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RequisitionApprover RequisitionApprover { get; set; }
    }
}
